In [1]:
import numpy as np

def prim_algorithm(graph):
    """
    Prim's algorithm to find the minimum spanning tree of a graph.
    
    Args:
    - graph (np.array): 2D numpy array representing an adjacency matrix of the graph,
                        where graph[i][j] represents the weight of the edge between i and j,
                        and a weight of 0 indicates no edge.
    
    Returns:
    - total_weight (int): The total weight of the minimum spanning tree.
    - mst_edges (list): List of edges in the minimum spanning tree.
    """
    num_vertices = graph.shape[0]
    # Array to track vertices not yet included in MST
    in_mst = np.zeros(num_vertices, dtype=bool)
    # Array to track minimum weight edge for each vertex
    min_edge = np.full(num_vertices, np.inf)
    # Parent array to store the MST
    parents = np.full(num_vertices, -1, dtype=int)

    # Start from the first vertex
    min_edge[0] = 0
    
    for _ in range(num_vertices):
        # Pick the minimum weight vertex from the set of vertices not yet included in MST
        u = np.argmin(min_edge[~in_mst])
        in_mst[u] = True  # Include vertex in MST
        
        # Update min weight edge and parent index of the adjacent vertices of the picked vertex
        for v in range(num_vertices):
            if graph[u, v] > 0 and in_mst[v] == False and min_edge[v] > graph[u, v]:
                min_edge[v] = graph[u, v]
                parents[v] = u
                
    total_weight = np.sum(min_edge)
    mst_edges = [(parents[i], i) for i in range(1, num_vertices) if parents[i] != -1]
    
    return total_weight, mst_edges

# Example usage
graph = np.array([
    [0, 5, 0, 5],
    [5, 0, 1, 2],
    [0, 1, 0, 4],
    [5, 2, 4, 0]
])

total_weight, mst_edges = prim_algorithm(graph)
print(f"Total weight of the minimum spanning tree: {total_weight}")
print("Edges in the minimum spanning tree:", mst_edges)


Total weight of the minimum spanning tree: inf
Edges in the minimum spanning tree: [(0, 1), (0, 3)]


In [3]:
graphNodeNo = graph.shape[0]
graphNodeNo

4

In [11]:
graph = np.array([
    [0, 5, 0, 5],
    [5, 0, 1, 2],
    [0, 1, 0, 4],
    [5, 2, 4, 0]
])
graph[graph ==0] = 7
print(graph)
mstNode = []

graphNodeNo = int(graph.shape[0])
res = np.zeros(graph.shape)
#append initial node
mstNode.append(0)

for _ in range(graphNodeNo):
    tempNext = []
    tempValue = []

    for node in mstNode:
        t = np.argmin(graph[node])
        tempNext.append(t)
        tempValue.append(graph[node][t])
    
    finNext = tempNext[np.argmax(tempValue)]
    mother = np.argmax(tempValue)
    print(node,tempNext, tempValue,finNext,mother)

    res[finNext][mother] = 1
    res[mother][finNext] = 1

    graph[node][finNext] = 7
    graph[finNext][node] = 7
    mstNode.append(finNext)
    print(res)
    print(graph)






[[7 5 7 5]
 [5 7 1 2]
 [7 1 7 4]
 [5 2 4 7]]
0 [1] [5] 1 0
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[7 7 7 5]
 [7 7 1 2]
 [7 1 7 4]
 [5 2 4 7]]
0 [3] [5] 3 0
[[0. 1. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]
[[7 7 7 7]
 [7 7 1 2]
 [7 1 7 4]
 [7 2 4 7]]
0 [0] [7] 0 0
[[1. 1. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]
[[7 7 7 7]
 [7 7 1 2]
 [7 1 7 4]
 [7 2 4 7]]
0 [0] [7] 0 0
[[1. 1. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]
[[7 7 7 7]
 [7 7 1 2]
 [7 1 7 4]
 [7 2 4 7]]


In [5]:
res

array([[1., 1., 1., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.]])